site_name: RingCentral Developer FAQ
site_url: https://developers.ringcentral.com
repo_url: https://github.com/ringcentral/ringcentral-faq
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'Overview', 'About']
- ['basics.md', 'FAQ', 'RingCentral Basics']
- ['oauth.md', 'FAQ', 'Authentication & Authorization']
- ['voice_ringout.md', 'FAQ', 'Voice via RingOut']
- ['voice_webrtc.md', 'FAQ', 'Voice via WebRTC']
- ['voice_recording.md', 'FAQ', 'Voice Call Recordings']
- ['sms.md', 'FAQ', 'SMS']
- ['fax.md', 'FAQ', 'Fax']
- ['api_usage_plan.md', 'FAQ', 'API Usage Plan']
- ['call_log.md', 'FAQ', 'Call Log']
- ['phone_numbers.md', 'FAQ', 'Phone Numbers']
- ['notifications_subscriptions.md', 'FAQ', 'Notifications & Subscription']
- ['errors.md', 'FAQ', 'Errors']
